INSERT INTO simulaciones_preguntas(simulacion_id, pregunta_id, puesto_laboral, respuesta)
VALUES
    (101,11021,'Docencia','Aun no he tenido experiencias laborales, pero he podido participar en diversas entrevistas universitarias.'),
    (101,11020,'Docencia','Porque soy una persona con capacidades natas. Ademas, puedo solucionar problemas entorno a mi especialidad.'),
    (101,11013,'Docencia',	'Porque es una empresa lider en el pais, que cuenta con muchos beneficios laborales y siento que puedo aportar con ideas y/o soluciones para seguir creciendo a nivel nacional e internacional.'),
    (102,11017,'Gerente de logistica','Si coincide el puesto hacia mis expectativas a futuro ya que me apasiona lo que hago y siento que puedo aportar con muchas ideas.'),
    (102,11019,'Gerente de logistica','La creatividad y el trabajo en equipo ayudaran a tener exito en el puesto que estoy postulando.'),
    (102,11018,'Gerente de logistica','Mi mayor logro fue competir en un concurso de ciencias a nivel internacional representando al Peru.'),
    (103,11015,'Docencia','El mayor reto en mi vida fue dejar a mi familia para poder estudiar mi carrera en el extranjero.'),
    (103,11016,'Docencia','Mi curriculum tiene amplios aspectos sobre mi vida estudiantil. Ademas, contiene todas las habilidades que he logrado durante el tiempo y las fortalezas que me definen.'),
    (103,11012,'Docencia','Mi mayor defecto es que soy impaciente.'),
    (104,11012,'Recursos Humanos','Intento ser muy perfeccionista en todo lo que hago y eso a veces lo considero como un defecto.'),
    (104,11015,'Recursos Humanos','La mejor decision que tome en mi vida fue la de independizarme, logrando mis objetivos por merito propio.'),
    (104,11014,'Recursos Humanos','En mi tiempo libre me gusta leer libros o aprender cosas nuevas a traves de videos en Youtube.'),
    (105,11013,'Programador','Porque la empresa va con mis habilidades, puedo aportar con ideas y ademas, hay un buen salario economico.'),
    (105,11012,'Programador','Soy poco tolerante con las personas.'),
    (105,11011,'Programador','Siento que mi personalidad y el carisma que tengo me hacen diferente de los otros candidatos.'),
    (106,11022,'Gerente de logistica','A corto plazo espero trabajar en una empresa como la suya, con una mision basada en una brillante difusion de su marca. Trabajar como gerente de logistica para una empresa en la que deseo que contribuya en mi preparacion para ir asumiendo responsabilidades cada vez mas amplias como liderar un equipo en el futuro.'),
    (106,11020,'Gerente de logistica','La verdad es que cuando he leido la oferta de empleo parecia hecha para mi. Estan buscando un ingeniero bilingüe en portugues, que aprenda rapido y que tenga capacidad para trabajar en un equipo multidisciplinar.  Y ese soy yo. Ingeniero industrial con amplias fortalezas.'),
    (107,11012,'Administrador de tecnologias de la informacion','Me niego a creer que puedo resolver cualquier problema por mi cuenta. Esto funciona bien en algunas situaciones, pero en muchos casos, necesito la ayuda de otros para superar factores fuera de mi control. En un caso el año pasado, estaba organizando un evento para clientes que tenia muchos componentes diferentes.'),
    (107,11014,'Administrador de tecnologias de la informacion','En mi tiempo libre me gusta asistir a talleres de liderazgo, ver videos de tecnologias actuales a nivel mundial, navegar y postear fotos en mis redes sociales.'),
    (108,11018,'Docencia','Uno de mis mayores logros fue pertenecer al grupo competitivo de marketing de empresas a nivel mundial, el estudiar en el extranjero siendo becado tambien lo considero como un logro.'),
    (108,11014,'Docencia','En mi tiempo libre practico mi habla y escritura en ingles para poder en un futuro, trabajar en una empresa americana lider en ciencias economicas y empresariales.'),
    (109,11020,'Programador','Tengo la habilidad para resolver situaciones potencialmente dificiles, especialmente en el ambito de programacion orientada a objetos. He logrado comprender y dominar lenguajes como C++, Python y JavaScript. Me resulta muy facil trabajar en equipo, puedo ser lider tranquilamente.'),
    (109,11022,'Programador','Mis metas son poder trabajar en una empresa lider a nivel mundial ya sea Google, Microsoft, Apple, etc. Tambien quisiera crear mi propio lenguaje de programacion, que le resulte util y tenga una alta demanda entre ingenieros como yo.');
